/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function parseChatMessages(file?: string | undefined | null): Array<Record<string, string | undefined | null>>
export function parseEvents(path: string, eventName: string, extraPlayer?: Array<string> | undefined | null, extraOther?: Array<string> | undefined | null): string
export function parseTicks(path: string, wantedProps: Array<string>): string
export function parsePlayerInfo(path: string): Array<Record<string, string | undefined | null>>
